### ISSUE TITLE
Outdated README/version number

### ISSUE THREAD

**Issue by MementoMakoMori** [MyHomeAutomations/python-actioncable-zwei#12]
I'm still getting the hang of github, so I apologize if posting this as an issue is breaking etiquette or if I am supposed to mention it another way?
This package is very useful, but unfortunately the readme hurts more than it helps.

- using pip install <package-name> will install an older version that does not have the December 2019 changes (so it will not work). changing the instruction to pip install git+https.... would fix it easily, but I don't know if the owner wants to update Pypi as well
- the version number on Pypi is identical to the version number in this repo's setup.py (which makes the first issue more difficult to figure out)
- in my uses, Message objects from ActionCable were structured in a way that has no 'action' and 'data' properties. I don't know if this is specific to the site I was contacting, but readme template for the on_receive callback function would not work until I realized that and removed them.

**Comment by 0x7466** [comment]
Welcome! You can send a pull request for the updates and I will merge the updated version. Happy giting!
