### ISSUE TITLE
Running example code does not connect to server

### ISSUE THREAD

**Issue by nicw** [MyHomeAutomations/python-actioncable-zwei#2]
When I copy the examples and run them, nothing happens. Meaning, my rails server shows no connection. I know the URL to be correct

Using the example Connect code

 ```
   from actioncable.connection import Connection
    from actioncable.subscription import Subscription
    
    connection = Connection(url='ws://localhost:3000/cable', origin='http://localhost:3000')
    connection.connect()
    
```

When I run this, the rails server shows no new connections

```
Puma starting in single mode...
* Version 3.8.2 (ruby 2.3.0-p0), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
```

**Comment by 0x7466** [comment]
Hi.

I've tested exactly the code you provided and it worked without problems on my machine.
Have you tested to connect to the server with another client to see if the problem is really caused by ActionCableZwei?

Best

**Comment by nicw** [comment]
Hi Tobias, thanks again. Connecting works with websocket-client and the code below. Meaning, the server shows it received a connect attempt. I'm stumped. It's the same URL. And I've allowed _all_ remote origins in my rails server.

Debug Output when I connect using example code (I added one to the runforever area)
```
python3 ./my_actioncable.py
04/03/2017 09:53:14 PM my_actioncable INFO: Started
04/03/2017 09:53:14 PM monitor DEBUG: ACTIONCABLE MONITOR : Started.
04/03/2017 09:53:14 PM connection DEBUG: ACTIONCABLE CONNECTION : RUN FOREVER...
04/03/2017 09:53:14 PM connection DEBUG: ACTIONCABLE CONNECTION : Connect...
$ (end)
```

Here is the example code from websocket-client
```
import websocket
import thread
import time
import json

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    msg = {'identifier': 'status_channel', 'command': 'message','message': 'FROM PYTHON'}
    

    
    def run(*args):
        for i in range(3):
            time.sleep(1)

            ws.send("{\"command\":\"subscribe\",\"identifier\":{\"channel\":\"MeshRelayChannel\"}}")
        time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())


if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("ws://localhost:3000/cable/",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()
```

**Comment by nicw** [comment]
Update: It works if I change line 54 of connection.py to call ws.run_forever() , instead of the internal function you have defined (_run_forever)

The thread isn't executing the `ws` instance, so nothing gets kicked off. But I'm not sure why this works for you and not me?

```self.ws_thread = threading.Thread(name="APIConnectionThread_{}".format(uuid.uuid1()), target=self.ws.run_forever())```

**Comment by 0x7466** [comment]
You actually call the `run_forever` method in your code. So the websocket connection will now block your main thread. You have to pass the reference to the new thread, so without parentheses.

BTW The private method I use as thread loop does actually also nothing other than calling the `run_forever` method of the `ws`. See [here](https://github.com/MyHomeAutomations/python-actioncable-zwei/blob/master/actioncable/connection.py#L80).

Are you trying to call this program directly from the command line like in the example above?

**Comment by nicw** [comment]
I see that now, your private method does end up calling the `run_forever` method of the `ws`. And yes, it does block the main thread (undesired!) but my server does receive responses.

Yes, I am trying to call this program directly. I am copying and pasting your code directly into a file, and then running 'python3 my_actioncable.py' Should I be running it differently, and I'm not understanding how to use this example?

I am running: python 3.6.1, macOS 10.12.3

**Comment by 0x7466** [comment]
Then add this code at the end of your file:

```python
while True:
  pass
```

The connection thread is actually a daemonic thread so it's going to be killed if the main thread finishes. If you call an infinite loop in the main thread this will actually never stop and your connection should be established.

**Comment by nicw** [comment]
Ahh, I see, that makes total sense. Threading 101. Thanks so much for putting with a newbie python guy. I really appreciate that you wrote this.

**Comment by 0x7466** [comment]
Your welcome :) Have fun!

Best
