### ISSUE TITLE
Unable to send cookie using ActionCableZwei

### ISSUE THREAD

**Issue by pj-parthjoshi** [MyHomeAutomations/python-actioncable-zwei#6]
Using:

- Python 2.7.12
- Rails 5.1.2
- Ruby 2.4.1

I am using ActionCable on webpage which works fine in rails, now trying to connect from python using https://github.com/tobiasfeistmantl/python-actioncable-zwei ActionCableZwei - A Python 3 client for Rails' Action Cable

Below line connects successfully:
`connection = Connection(url='ws://localhost:4000/cable', origin='http://localhost:4000/')`

and I get proper logs in rails.

Now, I want to send cookies with sockets but Below line is unable to connect nor do I get any logs in rails.
`connection = Connection(url='ws://localhost:4000/cable', origin='http://localhost:4000/', log_ping=False, cookie=coo)`

Also tried using log_ping to True/False

Below is full code that am trying:
```python
from actioncable.connection import Connection
from actioncable.subscription import Subscription
from actioncable.message import Message
import datetime
import random
from time import sleep
import Cookie 

coo = Cookie.SimpleCookie()
coo["fig"] = "newton"
coo["sugar"] = "wafer"

# connection = Connection(url='ws://localhost:4000/cable', origin='http://localhost:4000/')
connection = Connection(url='ws://localhost:4000/cable', origin='http://localhost:4000/', cookie=coo)
connection.connect()

subscription = Subscription(connection, identifier={'channel': 'TestChannel'})
subscription.create()

sleep(30)

subscription.remove()
connection.disconnect()
```
I just don't get any ping/log in rails about trying to connect. How can I fix this?

**Comment by 0x7466** [comment]
Have you tested it with Python 3?

**Comment by pj-parthjoshi** [comment]
No, Now will test with python 3 and will let you know

**Comment by pj-parthjoshi** [comment]
Tested in Python 3.5.2 , not working

**Comment by 0x7466** [comment]
Test to create the connection directly with the websocket client and see if there is a Rails response:

Something like this:

```ruby
import websocket

def on_event:
    pass

ws = websocket.WebSocketApp(
    <your_url>,
    cookie=<your_cookie>,
    on_message=on_event,
    on_close=on_event)

ws.run_forever(ping_interval=5, ping_timeout=3, origin=self.origin)
```

**Comment by pj-parthjoshi** [comment]
Testing with above code does not respond but if i remove cookie param like below then it responds in rails
`ws = websocket.WebSocketApp('ws://localhost:4000/cable',on_message=on_event,on_close=on_event)`

Do, i need to check about websocket module version or something like that ?
Edited: websocket-client==0.44.0 is the version

Am mostly from rails background, so you might need to support me :)

Also one trick, can you support for header in websockets ?
ref: https://github.com/websocket-client/websocket-client/blob/9a28437252c7c953e208ed07ff1811d1dc7b8c41/websocket/_app.py#L58

**Comment by 0x7466** [comment]
It looks like it's a bug in the `websocket-client` lib. But you could try an older version of the library or use the new added header parameter.
