### ISSUE TITLE
Cant suscribe to Channels, get stuck in 'pending' state

### ISSUE THREAD

**Issue by eterrones** [MyHomeAutomations/python-actioncable-zwei#8]
Hi! Iḿ having a similar problem, i get connected to my localhost server but my subscription is stuck at pennding state, so i do not recieve any messages nor can send them.

```
from actioncable.connection import Connection
from actioncable.subscription import Subscription

connection = Connection(url='ws://localhost:3000/cable', origin='http://localhost:3000')
connection.connect()
sleep(3)
print(connection.connected) #this is True
subscription = Subscription(connection, identifier={'channel': 'RaspiCommChannel'})
subscription.create()
```

If I check subscription state is 'pending' allways.
I try it from python console, using Python 3.7.2.
Can you help me please? Thanks!

_Originally posted by @eterrones in https://github.com/tobiasfeistmantl/python-actioncable-zwei/issues/4#issuecomment-472834533_

**Comment by brandonsturgeon** [comment]
I believe a websocket will _always_ be "pending". I think that's the correct state for it to be in. Have you checked your rails logs to see that the websocket connection was recognized and properly upgraded?
